name: AWS Amplify Deployment

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Test build
      run: npm run build
    
    - name: Test build artifacts
      run: |
        ls -la dist/
        test -f dist/index.html
        test -f dist/chat-widget.js
        echo "Build artifacts verified successfully"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-node-${{ matrix.node-version }}
        path: dist/
        retention-days: 7

  security-scan:
    runs-on: ubuntu-latest
    needs: test-build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run security audit
      run: npm audit --audit-level=moderate
    
    - name: Check for vulnerabilities
      run: npm audit --audit-level=high --production

  notify-amplify:
    runs-on: ubuntu-latest
    needs: [test-build, security-scan]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Notify successful pre-deployment checks
      run: |
        echo "✅ All pre-deployment checks passed"
        echo "🚀 AWS Amplify will automatically deploy from main branch"
        echo "📊 Monitor deployment at: https://console.aws.amazon.com/amplify/"
